### ISSUE TITLE
Add example to clarify instructions

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/cz-freecodecamp#1]
The instruction "Write a short, imperative tense description of your change" can be unclear for non-native English speakers. This could be clarified by adding an example. "E.g. Fix formatting for challenge X".

Also, a question: This is a CLI right? Then it would break my git editor setup?

**Comment by BerkeleyTrue** [comment]
👍 

Yes this is a CLI and will not work with visual git things.
