### ISSUE TITLE
should allow some numbers in subject

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/cz-freecodecamp#18]
https://github.com/freeCodeCamp/cz-freecodecamp/blob/master/index.js#L1
This currently in is catching all numbers. For example: 
`add es6 globals` is rejected

cc @erictleung @raisedadead

**Comment by erictleung** [comment]
@BerkeleyTrue [these lines of code](https://github.com/freeCodeCamp/cz-freecodecamp/blob/master/index.js#L55-L58) prevent numbers to be injected in the title.

We might be able to come up with a more elegant solution, but here's a quick solution just off the top of my head. The main repository issue numbers are now in the thousands. So we could change the regex to reject mentions of numbers with 4 or more digits.

```js
const noIssueNumbers = /#?\d{4,}/g;
```

**Comment by BerkeleyTrue** [comment]
Keep in mind that we are not building this module specifically for fcc but for anyone to use (I use it on many of my projects). 

We want it to only identify numbers that are isolated (surrounded by whitespace) or starting with the issue number hash. The current regex doesn't seem to work. It has a false positive with `es6`.

**Comment by erictleung** [comment]
@BerkeleyTrue ah that makes sense :+1: This might work then.

```js
const noIssueNumbers = /\s#?\d+\s?/g;
```

I'll submit a PR for this.
