### ISSUE TITLE
Accommodate questions to close issues from commit message

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/cz-freecodecamp#8]
~~~Should we remove [these lines of code](https://github.com/freeCodeCamp/cz-freecodecamp/blob/master/index.js#L67-L73) that ask for issues closed by a given commit? If we use this in the main repository, [we've asked that there be no issue numbers in the title or body](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps).~~~

## Issue

Right now, the commit title allows for anything e.g. issue numbers. They shouldn't be allowed. Additionally, if an issue number is referenced in the questions, you have to put `Closes #xxx` explicitly. Otherwise, it will just append whatever you input

## To Do

- [x] Prevent issue numbers to be in the commit title (regex for `/#\d+/`) (https://github.com/freeCodeCamp/cz-freecodecamp/pull/13)
- [ ] Fix the appending of issue numbers so that it has the keyword `Closes` before all issue numbers (https://github.com/freeCodeCamp/cz-freecodecamp/pull/14)
- [ ] Allow comma separated list of issues (https://github.com/freeCodeCamp/cz-freecodecamp/pull/14)

**Comment by BerkeleyTrue** [comment]
Hmm... Has this always been the case? I don't see any issues with including issue numbers in commit body's and PR comments. 

Originally I wanted to make sure issue numbers were not added to titles as then GitHub will not link the PR to the title becomes much less readable.

I don't see why the second part of this has been added.

**Comment by erictleung** [comment]
Ah okay. I wasn't sure where that rule came in. I knew of the convention of no issue numbers within the title. 

I'll change this issue to prevent issue numbers being in the title and update how the issues are referenced within the commitzen questioning (right now it literally adds what you input, without adding `Closes` before the number). If what I've outlined above don't make sense, let me know and I can change them to what you had in mind.

**Comment by erictleung** [comment]
@BerkeleyTrue after my changes in #14 are merged, I think this plugin should be good to go. You have plans on pushing this package up to npm so we can `npm install` it and use in conjunction with the main freeCodeCamp repository? I wasn't sure what the long-term goals of this plugin were.
